version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    networks: ["nats"]
  nats-1:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    networks: ["nats"]

  api:
    build: 
      context: api
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    volumes: 
      - ./api/app:/app
    networks: ["nats"]
    env_file: 
      - .env
  routeur:
    build: 
      context: routeur
      dockerfile: Dockerfile
    networks: ["nats"]
    env_file: 
      - .env
networks:
  nats:
    name: nats