version: "3.5"
services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      env_file:
        - .env 
      ports:
        - 5672:5672
        - 15672:15672
      networks: ["sgenet"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks: ["sgenet"]

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    networks: ["sgenet"]
    restart: unless-stopped
    env_file: 
      - .env

  api:
    build: 
      context: api
      dockerfile: Dockerfile
    networks: ["sgenet"]
    env_file: 
      - .env
    ports:
      - 8888:8888

  dispatcher:
    build: 
      context: dispatcher
      dockerfile: Dockerfile
    networks: ["sgenet"]
    env_file: 
      - .env
    ports:
      - 8881:8881

  event-logger:
    build: 
      context: event-logger
      dockerfile: Dockerfile
    networks: ["sgenet"]
    env_file: 
      - .env
    ports:
      - 8882:8882
networks:
  sgenet:
    name: sgenet